trigger:
  batch: true
  branches:
    include:
    - iis
  paths:
    exclude:
    - README.md
    - HELP.md

jobs:
# - template: Templates/build-publish-dotnetcore.yml
- template: Templates/build-test-publish-dontnetcore.yml
  parameters:
    name: BuildWebApp
    project: '**/TodoListWebApp/*.csproj'
    buildConfiguration: Debug
    artifactName: TodoList.WebApp
    vmImage: 'vs2017-win2016'